.text
.globl __bootstrap

__bootstrap:
    move r0, 0x0
    move r1, 0x0
    move r2, 0x0
    move r3, 0x0
    move r4, 0x0
    move r5, 0x0
    move r6, 0x0
    move r7, 0x0
    move r8, 0x0
    move r9, 0x0
    move r10, 0x0
    move r11, 0x0
    move r12, 0x0
    move r13, 0x0
    move r14, 0x0
    move r15, 0x0
    move r16, 0x0
    move r17, 0x0
    move r18, 0x0
    move r19, 0x0
    move r20, 0x0
    move r21, 0x0
    move r22, 0x0
    move r23, 0x0

    stop t, __bootstrap